#!/bin/bash

# TypeDef | Defining the File Types
version="0.62"
extension_url="https://raw.githubusercontent.com/abhishtagatya/typeDef/master/extension.json"

#TODO :
# - Create a feature list (Report, Update, Issue)
#   - Report : Report for Misinformation and anything about the 'extension.json'
#   - Update : Test Out the Update script feature
# - Create Test with python
# - Clean Code with ShellCheck
# Log(12 March 2018)

showHelp() {
  # Put A Help Function Here!
  printf 'typeDef - returns information of a file extension '
  printf "[version $version]\n"

  printf 'Usage: typedef [options] [file]\n\n'
  printf '\ttypdeDef is a tool that returns wiki information of various file\n'
  printf '\textension and outputting the name, developer, type and description\n'
  printf '\tof the given file.\n'
  printf '\tFor more information, visit us at https://github.com/abhishtagatya/typeDef\n\n'

  printf '\tAvailable options :\n'
  printf '\t -i\t\tprint the file information;\n'
  printf '\t -l\t\tprint the link and file information;\n'
  printf '\t -lo\t\tprint only the link file information;\n'
  printf '\t -w\t\tprint and open link of the file information;\n'
  printf '\t -wo\t\topen link of the file information;\n'
  printf '\t -u\t\tupdate the script to a newer version;\n\n'
  printf '\t -h\t\tshow help;\n\n'

  printf 'Issue and report bugs and misinformation in the github issue page\n'

}

getJSONContent() {
  # Get JSON Content from 'extension_url' or process other arguments
  if [[ $check_key ]]; then
    printf "$json_content\n"
  else
    printf "Extension '$extension' not found! Issue us at https://github.com/abhishtagatya/typedef\n"
    file $fullfilename
  fi
}

# Get the File Extension and Filename
if [[ -z $2 ]]; then
  fullfilename=$1
else
  fullfilename=$2
fi

extension="${fullfilename##*.}"
filename="${fullfilename%.*}"

# Check for connections and get JSON Data
pingtest=$(ping -c 1 -W 5 8.8.8.8 > /dev/null)
if [[ $? -eq 0 ]]; then
  check_key=$(curl -s $extension_url | jq "has(\"$extension\")")
  json_content=$(curl -s "$extension_url" | jq --arg extension "$extension" ".[\"$extension\"][\"header\",\"developer\",\"category\",\"description\"]")
fi

# Control Flow
option=$1
case $option in
  -h|--help|'')
    # Show help
    showHelp
    ;;

  -v|--version)
    # Print current version
    printf "typedef %s\n" "$version"
    ;;

  -u|--update)
    # Update and Replace Script
    if [[ $pingtest -eq 0 ]]; then
      sudo wget https://raw.githubusercontent.com/abhishtagatya/typeDef/master/typedef
      sudo install -Dm 755 typedef /usr/bin/typedef
      sudo rm typedef
      printf "Successfully Updated\n"
    else
      printf "It seems there is a problem with your network, Try Again\n"
    fi
    ;;

  -l|--link|-lo|--link-only)
    # Print and Output link
    if [[ "$option" == "-l" || "$option" == "--link" ]]; then
      getJSONContent
    fi
    printf "https://fileinfo.com/extension/%s\n" "$extension"
    ;;

  -w|--web|-wo|--web-only)
    # Print and Open up web using xdg-open
    if [[ "$option" == "-w" || "$option" == "--web" ]]; then
      getJSONContent
    fi
    lynx 'http://fileinfo.com/extension/'"$extension"
    exit 0
    ;;

  -i|--info)
  # Retrieve Info of File
  getJSONContent
  ;;

  *)
  # By Default it will just give info of the file
  getJSONContent
esac
