#!/bin/bash

# TypeDef | Defining the File Types

version="0.5"
author="Abhishta Gatya"
extension_url="https://raw.githubusercontent.com/abhishtagatya/typeDef/master/extension.json"

#TODO :
# - Create a feature list (Report, Update, Issue)
# - Create Test with python
# - Clean Code with ShellCheck
# Log(12 March 2018)

showHelp() {
  # Put A Help Function Here!
  printf 'typeDef - returns information of a file extension '
  printf "[version $version]\n"

  printf 'Usage: typedef [options] [file]\n\n'
  printf '\ttypdeDef is a tool that returns information of various file\n'
  printf '\textension and outputting the name, developer, type and description\n'
  printf '\tof the given file.\n'
  printf '\tFor more information, visit us at https://github.com/abhishtagatya/typeDef\n\n'

  printf '\tAvailable options :\n'
  printf '\t -i\t\tprint the file information;\n'
  printf '\t -l\t\tprint the link and file information;\n'
  printf '\t -lo\t\tprint only the link file information;\n'
  printf '\t -w\t\tprint and open link of the file information;\n'
  printf '\t -wo\t\topen link of the file information;\n'
  printf '\t -h\t\tshow help;\n'

}

getJSONContent() {
  # Get JSON Content from 'extension_url' or process other arguments
  if [[ $check_key ]]; then
    if [[ $get_json != 'null' ]]; then
      printf "$json_content\n"
    else
      file $fullfilename
    fi
  fi
}

# Get the File Extension and Filename
if [[ $2 == "" ]]; then
  fullfilename=$1
else
  fullfilename=$2
fi

extension="${fullfilename##*.}"
filename="${fullfilename%.*}"

# Check for connections and get JSON Data
wget -q --timeout=20 --spider http://fileinfo.com
if [[ $? -eq 0 ]]; then
  check_key=$(curl -s $extension_url | jq "has(\"$extension\")")
  get_json=$(curl -s $extension_url | jq ".[\"$extension\"]")
  json_content=$(curl -s "$extension_url" | jq --arg extension "$extension" ".[\"$extension\"][\"header\",\"developer\",\"category\",\"description\"]")
else
  file $fullfilename
fi

# Control Flow
option=$1
case $option in
  -v|--version)
    # Print current version
    printf "typedef %s\n" "$version"
    ;;
  -h|--help)
    # Show help
    showHelp
    ;;
  -u|--update)
    # Update and Replace Script
    wget -q --timeout=20 --spider http://fileinfo.com
    if [[ $? -eq 0 ]]; then
      wget https://raw.githubusercontent.com/abhishtagatya/typeDef/master/typedef
      sudo install -Dm 755 typedef /usr/bin/typedef
      printf "Successfully Updated\n"
    else
      printf "It seems there is a problem with your network, Try Again\n"
    fi
    ;;
  -l|--link)
    # Print and Output link
    getJSONContent
    printf "https://fileinfo.com/extension/%s\n" "$extension"
    ;;
  -lo|--link-only)
    printf "https://fileinfo.com/extension/%s\n" "$extension"
    ;;
  -w|--web)
    # Print and Open up web using xdg-open
    getJSONContent
    xdg-open 'http://fileinfo.com/extension/'"$extension"
    ;;
  -wo|--web-only)
    # Only Open up web using xdg-open
    xdg-open 'http://fileinfo.com/extension/'"$extension"
    ;;
  -i|--info)
  getJSONContent
  ;;
  "")
  # Return help if no arg is given
  showHelp
  ;;
  *)
  # By Default it will just give info of the file
  getJSONContent
esac
